/**
 * pi-experiment-6q0y.50 — Cerdiwen follow-through audit regression fixture.
 *
 * GOAL
 * ----
 * Prove that every open Orr Else HARNESS bead has been audited for Cerdiwen
 * impact and assigned EXACTLY ONE of:
 *   - coverage: "edge"       — a graph-enforced cerdiwen follow-through bead
 *   - coverage: "no-impact"  — a deterministic reason Cerdiwen is unaffected
 *
 * The test reads ONLY the committed manifest file (never the live bd DB or
 * .beads/ directory) so results are deterministic in CI and across worktrees.
 *
 * LOAD-BEARING: this test FAILS if:
 *   - An AC7 bead (l3sw, t6gw, 85bl, 0ipk) is missing from the manifest.
 *   - Any entry has both or neither of followThroughBeadId / noImpactReason.
 *   - Any entry uses an impactArea outside the canonical AC2 vocabulary.
 *   - Any beadId appears more than once in the manifest.
 *   - Any bead in KNOWN_OPEN_HARNESS_BEAD_IDS is absent from the manifest
 *     (the completeness / superset guard — adding a new open harness bead
 *     without auditing it FAILS this test).
 */

import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Manifest path
// ---------------------------------------------------------------------------

const MANIFEST_PATH = path.join(
  __dirname,
  'fixtures',
  'cerdiwen-followthrough',
  'harness-bead-audit.json'
);

// ---------------------------------------------------------------------------
// AC2 canonical impact-area vocabulary
// ---------------------------------------------------------------------------

const CANONICAL_IMPACT_AREAS = new Set([
  'statechart',
  'active-tools',
  'prompt-profiles',
  'tool-evidence',
  'schemas',
  'budgets',
  'startup-lint',
  'context-policy',
  'fan-out-join',
  'loop-detection',
  'terminal-transition-admission',
  'project-tool-contracts',
  'readiness-probes',
  'scheduler',
  'query-tool-usage',
]);

// ---------------------------------------------------------------------------
// AC7 beads that MUST be present with a resolved coverage
// (l3sw, t6gw, 85bl, 0ipk — set by the 6q0y.50 orchestrator)
// ---------------------------------------------------------------------------

const AC7_BEAD_IDS = ['l3sw', 't6gw', '85bl', '0ipk'] as const;

// ---------------------------------------------------------------------------
// Completeness / superset guard (AC6)
// Every beadId listed here MUST appear in the manifest. To add a new open
// harness bead: add it here AND add an audit entry to harness-bead-audit.json.
//
// REGENERATION NOTE: This list is generated by reconciling
//   `bd list --status=open --limit 0` + `bd list --status=in_progress --limit 0`
// against the declared cerdiwen-consumer exclusions (follow-through targets) and
// epic-container IDs (1elr, 6q0y, amq0, dsm2, zog2 bare parents). It MUST be
// regenerated whenever a new harness bead is added to the bd database.
// AC5's planner/pre-reviewer guidance (see docs/cerdiwen-followthrough-audit.md)
// enforces this: every new harness bead must be audited here before the bead is
// closed. The committed test cannot read the live bd at runtime (deterministic
// CI constraint), so completeness is a process guarantee rather than a runtime
// assertion — this list is the process artifact that makes it load-bearing.
// ---------------------------------------------------------------------------

const KNOWN_OPEN_HARNESS_BEAD_IDS: readonly string[] = [
  // 6q0y epic harness beads
  '6q0y.5',
  '6q0y.9',
  '6q0y.17',
  '6q0y.18',
  '6q0y.19',
  '6q0y.24',
  '6q0y.25',
  '6q0y.26',
  '6q0y.32',
  '6q0y.35',
  '6q0y.36',
  '6q0y.37',
  '6q0y.39',
  '6q0y.40',
  '6q0y.46',
  '6q0y.47',
  '6q0y.48',
  '6q0y.49',
  '6q0y.50',
  // AC7 beads
  'l3sw',
  't6gw',
  '85bl',
  '0ipk',
  // amq0 modularization beads
  'amq0.1',
  'amq0.2',
  'amq0.3',
  'amq0.4',
  'amq0.5',
  'amq0.6',
  'amq0.7',
  'amq0.8',
  'amq0.9',
  'amq0.10',
  'amq0.11',
  'amq0.12',
  'amq0.13',
  'amq0.14',
  'amq0.15',
  'amq0.16',
  'amq0.17',
  'amq0.18',
  'amq0.19',
  'amq0.20',
  // 1elr startup-lint beads
  '1elr.1',
  '1elr.3',
  '1elr.4',
  '1elr.5',
  '1elr.6',
  '1elr.7',
  '1elr.10',
  '1elr.11',
  '1elr.12',
  // v2 config / startup-lint beads
  '6k8e',
  'cfzu',
  '0njv',
  '0dgy',
  'afdz',
  'hutg',
  'ne2w',
  'w2tz',
  'x0zh',
  'ux5e',
  '94u7',
  'ek2j',
  'e8cm',
  'se6g',
  '7ypp',
  'isjk',
  'vzp7',
  'nkiq',
  // tool-evidence harness beads
  'jxdk',
  'w8rz',
  'yhec',
  // zog2 tool-evidence beads
  'zog2.4',
  'zog2.5',
  'zog2.6',
  'zog2.10',
  'zog2.11',
  'zog2.13',
  'zog2.14',
  'zog2.17',
  'zog2.20',
  'zog2.21',
  'zog2.22',
  // dsm2 boundary-contract beads
  'dsm2.2',
  'dsm2.4',
  'dsm2.5',
  'dsm2.6',
  'dsm2.7',
  'dsm2.8',
  'dsm2.9',
  'dsm2.10',
  'dsm2.11',
  // cerdiwen-observed harness beads
  '6iae',
  'a9eq',
  '4ub5',
  'cim5',
  'ixtf',
  'yp1w',
  '2tb1',
  // additional harness beads
  'jvx3',
  'ebzz',
  'ejv1',
  'jfms',
  'migrated-hmp53.1',
  'rm9x',
  '0iyt',
];

// ---------------------------------------------------------------------------
// Type definitions (mirrors the manifest schema)
// ---------------------------------------------------------------------------

interface AuditEntry {
  beadId: string;
  title: string;
  impactAreas: string[];
  cerdiwenSurface: string;
  coverage: 'edge' | 'no-impact';
  followThroughBeadId?: string;
  noImpactReason?: string;
}

// ---------------------------------------------------------------------------
// Load the manifest once
// ---------------------------------------------------------------------------

function loadManifest(): AuditEntry[] {
  expect(
    fs.existsSync(MANIFEST_PATH),
    `Manifest not found at ${MANIFEST_PATH} — run bead 6q0y.50 to generate it`
  ).toBe(true);
  const raw = fs.readFileSync(MANIFEST_PATH, 'utf8');
  return JSON.parse(raw) as AuditEntry[];
}

const MANIFEST = loadManifest();

// ---------------------------------------------------------------------------
// (a) Every entry is well-formed
// ---------------------------------------------------------------------------

describe('(a) every audit entry is well-formed', () => {
  it('manifest is non-empty', () => {
    expect(MANIFEST.length).toBeGreaterThan(0);
  });

  it.each(MANIFEST.map(e => [e.beadId, e] as [string, AuditEntry]))(
    'entry %s: non-empty beadId and title',
    (_, entry) => {
      expect(entry.beadId.trim().length, `beadId must be non-empty`).toBeGreaterThan(0);
      expect(entry.title.trim().length, `title must be non-empty for ${entry.beadId}`).toBeGreaterThan(0);
    }
  );

  it.each(MANIFEST.map(e => [e.beadId, e] as [string, AuditEntry]))(
    'entry %s: at least one impactArea',
    (_, entry) => {
      expect(
        Array.isArray(entry.impactAreas) && entry.impactAreas.length >= 1,
        `${entry.beadId} must have at least one impactArea`
      ).toBe(true);
    }
  );

  it.each(MANIFEST.map(e => [e.beadId, e] as [string, AuditEntry]))(
    'entry %s: EXACTLY ONE of followThroughBeadId (edge) or noImpactReason (no-impact) — never both, never neither',
    (_, entry) => {
      const hasEdge = entry.coverage === 'edge' && typeof entry.followThroughBeadId === 'string' && entry.followThroughBeadId.length > 0;
      const hasNoImpact = entry.coverage === 'no-impact' && typeof entry.noImpactReason === 'string' && entry.noImpactReason.length > 0;

      const bothPresent = typeof entry.followThroughBeadId !== 'undefined' && typeof entry.noImpactReason !== 'undefined';
      const neitherPresent = typeof entry.followThroughBeadId === 'undefined' && typeof entry.noImpactReason === 'undefined';

      expect(
        bothPresent,
        `${entry.beadId}: must not have BOTH followThroughBeadId and noImpactReason`
      ).toBe(false);

      expect(
        neitherPresent,
        `${entry.beadId}: must have EITHER followThroughBeadId (coverage=edge) or noImpactReason (coverage=no-impact)`
      ).toBe(false);

      expect(
        hasEdge || hasNoImpact,
        `${entry.beadId}: coverage="${entry.coverage}" must match populated field — ` +
        `edge requires non-empty followThroughBeadId; no-impact requires non-empty noImpactReason`
      ).toBe(true);
    }
  );
});

// ---------------------------------------------------------------------------
// (b) AC7 beads are present with resolved coverage
// ---------------------------------------------------------------------------

describe('(b) AC7 beads (l3sw, t6gw, 85bl, 0ipk) are present with resolved coverage', () => {
  const byId = new Map(MANIFEST.map(e => [e.beadId, e]));

  it.each(AC7_BEAD_IDS)(
    'AC7 bead %s is in the manifest',
    (beadId) => {
      expect(
        byId.has(beadId),
        `AC7 bead ${beadId} must be present in the audit manifest`
      ).toBe(true);
    }
  );

  it('l3sw has coverage=edge pointing to 6q0y.10 (orchestrator follow-through edge)', () => {
    const entry = byId.get('l3sw');
    expect(entry).toBeDefined();
    expect(entry!.coverage).toBe('edge');
    expect(entry!.followThroughBeadId).toBe('6q0y.10');
  });

  it('t6gw has coverage=no-impact (Cerdiwen configures no retryPolicy)', () => {
    const entry = byId.get('t6gw');
    expect(entry).toBeDefined();
    expect(entry!.coverage).toBe('no-impact');
    expect(entry!.noImpactReason).toBeTruthy();
  });

  it('85bl has coverage=edge pointing to 6q0y.34 (orchestrator follow-through edge)', () => {
    const entry = byId.get('85bl');
    expect(entry).toBeDefined();
    expect(entry!.coverage).toBe('edge');
    expect(entry!.followThroughBeadId).toBe('6q0y.34');
  });

  it('0ipk has coverage=edge pointing to 6q0y.34 (orchestrator follow-through edge; idempotency side no-impact)', () => {
    const entry = byId.get('0ipk');
    expect(entry).toBeDefined();
    expect(entry!.coverage).toBe('edge');
    expect(entry!.followThroughBeadId).toBe('6q0y.34');
  });
});

// ---------------------------------------------------------------------------
// (c) Every impactArea is in the canonical AC2 vocabulary
// ---------------------------------------------------------------------------

describe('(c) all impactAreas are in the canonical AC2 vocabulary (drift guard)', () => {
  it.each(MANIFEST.map(e => [e.beadId, e] as [string, AuditEntry]))(
    'entry %s: all impactAreas are canonical',
    (_, entry) => {
      for (const area of entry.impactAreas) {
        expect(
          CANONICAL_IMPACT_AREAS.has(area),
          `${entry.beadId}: impactArea "${area}" is not in the canonical AC2 vocabulary.\n` +
          `Allowed: ${[...CANONICAL_IMPACT_AREAS].sort().join(', ')}`
        ).toBe(true);
      }
    }
  );
});

// ---------------------------------------------------------------------------
// (d) No duplicate beadId
// ---------------------------------------------------------------------------

describe('(d) no duplicate beadId in manifest', () => {
  it('all beadIds in the manifest are unique', () => {
    const seen = new Set<string>();
    const duplicates: string[] = [];
    for (const entry of MANIFEST) {
      if (seen.has(entry.beadId)) {
        duplicates.push(entry.beadId);
      }
      seen.add(entry.beadId);
    }
    expect(
      duplicates,
      `Duplicate beadIds found in manifest: ${duplicates.join(', ')}`
    ).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// (e) Completeness / superset guard (AC6)
// Every known open harness bead must appear in the manifest.
// Adding a new open harness bead without auditing it FAILS this test.
// ---------------------------------------------------------------------------

describe('(e) completeness guard: manifest covers every known open harness bead', () => {
  const manifestIds = new Set(MANIFEST.map(e => e.beadId));

  it('manifest covers all known open harness bead IDs', () => {
    const missing = KNOWN_OPEN_HARNESS_BEAD_IDS.filter(id => !manifestIds.has(id));
    expect(
      missing,
      `The following known open harness beads are absent from the audit manifest:\n` +
      missing.map(id => `  - ${id}`).join('\n') +
      `\nAdd audit entries to tests/fixtures/cerdiwen-followthrough/harness-bead-audit.json.`
    ).toHaveLength(0);
  });

  it(`KNOWN_OPEN_HARNESS_BEAD_IDS has ${KNOWN_OPEN_HARNESS_BEAD_IDS.length} entries`, () => {
    // This count is load-bearing: adding a new harness bead requires updating
    // KNOWN_OPEN_HARNESS_BEAD_IDS (increment this expected value) AND adding
    // an entry to the manifest JSON.
    expect(KNOWN_OPEN_HARNESS_BEAD_IDS.length).toBe(107);
  });
});
